name: Package Test (Native)
description: Unit tests + native ops tests via Makefile

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-fvm
    - uses: ./.github/actions/setup-rust
    - uses: ./.github/actions/debug-ssh
    - shell: bash
      run: make test-unit
    - shell: bash
      run: make test-ops-native
