name: Setup Linux
description: Headless display (xvfb) for Linux desktop tests.

inputs:
  xvfb:
    description: "Install xvfb for headless display"
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: xvfb
      if: inputs.xvfb == 'true'
      shell: bash
      run: sudo apt-get update -qq && sudo apt-get install -y -qq xvfb
