// Hashes of pre-built native binaries downloaded by the build hook.
// Generated by tool/write_asset_hashes.dart after a release build.
//
// The build hook verifies downloaded files against these hashes.
// Hash mismatch → re-download. Correct → use cached. Missing → download.

const Map<String, String> assetHashesSha256 = {
  // Populated by tool/write_asset_hashes.dart after CI uploads release binaries.
  // Format: 'platform-libpdf_oxide.ext': 'sha256hex'
  //
  // Example (after release):
  // 'macos-arm64-libpdf_oxide.dylib': 'abc123...',
  // 'macos-x64-libpdf_oxide.dylib': 'def456...',
  // 'ios-arm64-libpdf_oxide.a': '...',
  // 'android-arm64-libpdf_oxide.so': '...',
  // 'linux-x64-libpdf_oxide.so': '...',
  // 'windows-x64-pdf_oxide.dll': '...',
  // 'windows-arm64-pdf_oxide.dll': '...',
};
