// Build hook for pdf_manipulator.
//
// ═══════════════════════════════════════════════════════════════════
// STRUCTURE
// ═══════════════════════════════════════════════════════════════════
//
//   main()           Flutter hook entry point (native targets only).
//                    Resolves the binary, registers it with Flutter.
//
//   resolveWeb()     Public API for bin/setup.dart (web assets).
//                    Same waterfall, no registration needed — Flutter
//                    serves web/ as static files.
//
//   _resolveNative() Private. Only main() calls this — the correct
//                    cache path and target config only exist inside
//                    the build hook. setup --native delegates to
//                    `flutter build` which triggers main().
//
// ═══════════════════════════════════════════════════════════════════
// RESOLUTION WATERFALL (same for native and web)
// ═══════════════════════════════════════════════════════════════════
//
//   1. CACHED    — existing file, only with a PROOF: hash match, or
//                  no-hash-AND-no-sources (nothing better exists).
//                  When vendor sources are present and there is no
//                  hash, this step always falls through — freshness
//                  is cargo's question, never file-existence.
//   2. DOWNLOAD  — fetch from GitHub Releases; verified against the
//                  pinned hash at download time (or used with a loud
//                  warning when neither hash nor source exists) → cache
//   3. COMPILE   — vendor/pdf_oxide/ exists → cargo (native and
//                  wasm; wasm adds the bindgen_runner crate) → use it
//   4. SUBMODULE — .gitmodules exists → git init recursive → compile
//   5. ERROR     — nothing worked, clear message with options
//
//   --force skips step 1 (web only, via setup.dart).
//   Version 0.0.0 (dev) skips step 2 (no release exists) — so every
//   dev build lands on step 3 and cargo's fingerprint check decides
//   whether anything actually recompiles (~1s when nothing changed).
//
// ═══════════════════════════════════════════════════════════════════
// USER SCENARIOS
// ═══════════════════════════════════════════════════════════════════
//
//   pub.dev consumer (pdf_manipulator: ^X.Y.Z):
//     Native: automatic via build hook. Downloads prebuilt binary.
//             If binary missing: compiles from vendor source (ships
//             in tarball).
//     Web:    manual `flutter pub run pdf_manipulator:setup`.
//             Same waterfall. Downloads or compiles.
//
//   Git tag consumer (ref: vX.Y.Z):
//     Same as pub.dev — tag has vendor source + release has binaries.
//
//   Git branch consumer (ref: dev, version 0.0.0):
//     Download skipped. Compiles from vendor source or inits
//     submodules first.
//
//   Contributor (path dependency):
//     Same as branch consumer. Always compiles from source.
//
// ═══════════════════════════════════════════════════════════════════
// STALENESS
// ═══════════════════════════════════════════════════════════════════
//
//   Native: fully automatic. Flutter re-runs the hook when
//     pubspec.yaml changes. New assetHashes → hash mismatch →
//     re-downloads.
//
//   Web: NOT automatic. User must run `setup` after package update.
//     Hash check detects stale files and re-resolves automatically.
//     Tracked: dart-lang/native#988 (WasmAsset/JsAsset support).
//
// ═══════════════════════════════════════════════════════════════════
// ASSET HASHES
// ═══════════════════════════════════════════════════════════════════
//
//   Flat Map<String, String> keyed by GitHub Release asset name.
//   Generated by tool/ci/release.sh --update-tag-hashes from:
//     1. GitHub Release API digests (native + WASM build outputs)
//     2. Local SHA-256 of hand-written JS (lane_worker.js)

import 'dart:io';

import 'package:code_assets/code_assets.dart';
import 'package:hooks/hooks.dart';
import 'package:logging/logging.dart';
import 'package:path/path.dart' as p;

import 'package:pdf_manipulator/src/hook/asset_hashes.dart';
import 'package:pdf_manipulator/src/hook/build_constants.dart';
import 'package:pdf_manipulator/src/hook/engine_build.dart';
import 'package:pdf_manipulator/src/hook/app_root.dart';
import 'package:pdf_manipulator/src/hook/engine_compiler.dart';
import 'package:pdf_manipulator/src/hook/resolver.dart';
import 'package:pdf_manipulator/src/hook/keep_plan.dart';
import 'package:pdf_manipulator/src/hook/pdf_config.dart';

final _log = Logger('pdf_manipulator:build');

const _assetId = 'src/ffi/native_bindings.g.dart';

// ══════════════════════════════════════════════════════════════════
// § 1 — Flutter hook entry point (native only)
//
// Called automatically for iOS, Android, macOS, Linux, Windows.
// NOT called for web — web goes through resolveWeb() via setup.dart.
// ══════════════════════════════════════════════════════════════════

void main(List<String> args) async {
  await build(args, (BuildInput input, BuildOutputBuilder output) async {
    if (!input.config.buildCodeAssets) return;

    final constants = BuildConstants.load(input.packageRoot);
    // The build-hook API exposes user-defines by key, not as a key set — so
    // build the map from the known keys and let the one parser validate it.
    // (Unknown-key rejection needs the full key set, which only the web path
    // has; native leans on the value-grammar + axis-mismatch checks.)
    final ud = input.userDefines;
    final cfg = PdfManipulatorConfig.parse({
      for (final k in PdfManipulatorConfig.knownKeys)
        if (ud[k] != null) k: ud[k],
    });
    final engineBuild = cfg.build;
    final plan = await resolveKeepPlan(
      keep: cfg.keep,
      detector: cfg.detector,
      defaultFeatures: constants.nativeFeatures,
      // NOT Directory.current: the runner starts every hook with its
      // working directory set to the package's OWN root, so reading it
      // scans pdf_manipulator, finds every capability where it is
      // implemented, and keeps all of them. The output directory is the
      // only handle on the consuming app a build hook is given.
      appRootCandidate: appRootFromHookOutput(input.outputDirectory),
      scanDirs: cfg.scanDirs,
    );
    if (plan.deferToLink && !input.config.linkingEnabled) {
      stderr.writeln(
        'pdf_manipulator detector record-use: linking is disabled in '
        'this build (debug) — shipping the FULL binary. Release builds '
        'trim in the link hook.',
      );
    }

    final codeConfig = input.config.code;
    final targetTriple = targetTripleFor(codeConfig);
    final linkMode = linkModeFor(codeConfig);
    final libFileName = codeConfig.targetOS.libraryFileName(
      constants.crate,
      linkMode,
    );
    final outFile = File.fromUri(input.outputDirectory.resolve(libFileName));

    // ── Resolve the binary (download, compile, or cache) ──
    await _resolveNative(
      constants: constants,
      plan: plan,
      engineBuild: engineBuild,
      packageRoot: input.packageRoot,
      version: readVersion(input.packageRoot),
      targetKey: targetKeyFor(codeConfig),
      libFileName: libFileName,
      dest: outFile,
      cacheFile: File.fromUri(
        input.outputDirectoryShared.resolve('$targetTriple/$libFileName'),
      ),
      targetTriple: targetTriple,
      linkMode: linkMode,
      buildInput: input,
    );

    // ── Register with Flutter ──
    _registerCodeAsset(input, output, outFile, linkMode);
    _registerDependencies(input, output);
    // The app source the keep decision was derived from. Without this the
    // runner caches the decision and never re-runs the hook, so an app that
    // starts calling a trimmed-away capability keeps building without it.
    output.dependencies.addAll(plan.appDependencies);
  });
}

// ══════════════════════════════════════════════════════════════════
// § 2 — Resolution
// ══════════════════════════════════════════════════════════════════

// ── Native (private) ─────────────────────────────────────────────
// Not public because the correct cache path, target triple, link
// mode, and NDK config all come from Flutter's BuildInput — which
// only exists inside the hook. Calling from outside writes to the
// wrong cache. setup --native delegates to `flutter build` instead.
Future<void> _resolveNative({
  required BuildConstants constants,
  required KeepPlan plan,
  required EngineBuild engineBuild,
  required Uri packageRoot,
  required String version,
  required String targetKey,
  required String libFileName,
  required File dest,
  required File cacheFile,
  required String targetTriple,
  required LinkMode linkMode,
  required BuildInput buildInput,
}) async {
  final assetName = '$targetKey-$libFileName';

  // Prebuilt release binaries exist ONLY for the default feature set on the
  // default (speed) build. A kept subset or a non-default build (size/debug)
  // has no prebuilt and no pinned hash: version 0.0.0 routes the resolver
  // straight to compile, and cargo's own fingerprint is the cache.
  final custom = plan.isCustom || !engineBuild.isDefault;
  final effectiveVersion = custom ? '0.0.0' : version;

  await resolveAsset(
    ResolveRequest(
      assetName: assetName,
      downloadUrl: constants.downloadUrl(effectiveVersion, assetName),
      dest: dest,
      cacheFile: custom ? null : cacheFile,
      expectedHash: custom ? null : assetHashes[assetName],
      version: effectiveVersion,
      packageRoot: packageRoot,
      compile: (File d) => _compileNativeFromHook(
        buildInput,
        targetTriple,
        linkMode,
        d,
        constants,
        plan,
        engineBuild,
      ),
    ),
  );
}

// ── Web (public — called by bin/setup.dart) ──────────────────────
// Resolves WASM + JS into destDir (typically web/pdf_manipulator/).
// Flutter serves destDir as static files — no registration needed.
//
// Two asset types with different compile fallbacks:
//   WASM build outputs (pdf_oxide_bg.wasm, pdf_oxide.js) → cargo + bindgen_runner
//   Hand-written JS (lane_worker.js) → copy from package
//
// Returns the number of files freshly resolved (0 = all cached).
Future<int> resolveWeb({
  required Uri packageRoot,
  required String version,
  required Directory destDir,
  bool force = false,
  String? wasmFeaturesOverride,
  EngineBuild engineBuild = EngineBuild.speed,
}) async {
  final constants = BuildConstants.load(packageRoot);
  // A kept subset OR a non-default build has no prebuilt asset, no pinned
  // hash, and must not reuse a default-set artifact: force + version 0.0.0
  // route the resolver straight to a fresh compile.
  final custom = wasmFeaturesOverride != null || !engineBuild.isDefault;
  final effectiveVersion = custom ? '0.0.0' : version;
  final effectiveForce = force || custom;

  if (!destDir.existsSync()) {
    destDir.createSync(recursive: true);
  }

  var installed = 0;

  for (final entry in constants.webAssets.entries) {
    final localName = entry.key;
    final assetName = entry.value;
    final dest = File('${destDir.path}/$localName');

    final isWasmBuildOutput = constants.wasmBuildOutputs.contains(localName);

    final fresh = await resolveAsset(
      ResolveRequest(
        assetName: assetName,
        downloadUrl: constants.downloadUrl(effectiveVersion, assetName),
        dest: dest,
        expectedHash: custom ? null : assetHashes[assetName],
        version: effectiveVersion,
        packageRoot: packageRoot,
        force: effectiveForce,
        compile: isWasmBuildOutput
            ? (File d) => _compileWasm(
                packageRoot,
                d,
                localName,
                wasmFeaturesOverride,
                engineBuild,
              )
            : (File d) => _copyWebAsset(packageRoot, d, localName),
      ),
    );

    if (fresh) installed++;
  }

  return installed;
}

// ══════════════════════════════════════════════════════════════════
// § 3 — Flutter registration (native only)
// ══════════════════════════════════════════════════════════════════

/// Register the native binary as a code asset.
/// Release/AOT routes through hook/link.dart (passthrough today —
/// see hook/link.dart for the tree-shaking roadmap).
void _registerCodeAsset(
  BuildInput input,
  BuildOutputBuilder output,
  File outFile,
  LinkMode linkMode,
) {
  output.assets.code.add(
    CodeAsset(
      package: input.packageName,
      name: _assetId,
      linkMode: linkMode,
      file: outFile.uri,
    ),
    routing: input.config.linkingEnabled
        ? ToLinkHook(input.packageName)
        : const ToAppBundle(),
  );
}

/// Register files Flutter should watch. Any change re-runs the hook;
/// cargo then decides what to actually recompile.
///
/// Must over-approximate cargo's inputs and must exist BEFORE the
/// first build — never derive this list from build outputs like
/// cargo dep-info, or caching goes circular and binaries go stale.
void _registerDependencies(BuildInput input, BuildOutputBuilder output) {
  output.dependencies.add(input.packageRoot.resolve('hook/build.dart'));
  output.dependencies.add(input.packageRoot.resolve('pubspec.yaml'));
  output.dependencies.add(input.packageRoot.resolve('build.json'));

  if (hasVendorSource(input.packageRoot)) {
    for (final crate in const ['vendor/pdf_oxide', 'vendor/office_oxide']) {
      _registerCrateSources(input, output, crate);
    }
  }
}

/// Register one vendored crate's buildable inputs: manifest, lock
/// file, build script, toolchain/flags config, and EVERY file under
/// src/ — not just .rs (include_bytes! assets are inputs too).
void _registerCrateSources(
  BuildInput input,
  BuildOutputBuilder output,
  String crate,
) {
  const configs = [
    'Cargo.toml',
    'Cargo.lock',
    'build.rs',
    'rust-toolchain.toml',
    'rust-toolchain',
    '.cargo/config.toml',
    '.cargo/config',
  ];
  for (final file in configs) {
    final uri = input.packageRoot.resolve('$crate/$file');
    if (File.fromUri(uri).existsSync()) {
      output.dependencies.add(uri);
    }
  }

  final srcDir = Directory.fromUri(input.packageRoot.resolve('$crate/src'));
  if (!srcDir.existsSync()) return;
  var registered = 0;
  for (final entry in srcDir.listSync(recursive: true)) {
    if (entry is File) {
      output.dependencies.add(entry.uri);
      registered++;
    }
  }
  _log.info('registered $registered source files from $crate/src');
}

// ══════════════════════════════════════════════════════════════════
// § 4 — Compile callbacks
// ══════════════════════════════════════════════════════════════════

// ── Native: from build hook (has BuildInput with NDK, triple) ────

Future<void> _compileNativeFromHook(
  BuildInput input,
  String targetTriple,
  LinkMode linkMode,
  File outFile,
  BuildConstants constants,
  KeepPlan plan,
  EngineBuild engineBuild,
) async {
  final codeConfig = input.config.code;
  await compileEngineForTarget(
    packageRoot: input.packageRoot,
    crateName: constants.crate,
    targetTriple: targetTriple,
    features: plan.features,
    targetDir: p.join(p.fromUri(input.outputDirectory), 'cargo_target'),
    libFileName: codeConfig.targetOS.libraryFileName(constants.crate, linkMode),
    outFile: outFile,
    environment: {
      ...androidLinkerEnv(codeConfig, targetTriple),
      ...engineBuild.cargoEnv,
    },
  );
}

// ── Web: WASM build outputs (pdf_oxide.js + pdf_oxide_bg.wasm) ───
//
// Pure Dart + cargo, like the native hook path: compile the engine to
// wasm32, then run the workspace's own bindgen_runner crate, which
// executes wasm-bindgen and wasm-opt as library calls resolved from the
// engine's Cargo.lock. No wasm-bindgen-cli, binaryen, or jq installs —
// Rust is the only requirement — and the CLI-vs-crate version drift of
// issue #177 is structurally impossible.

Future<void> _compileWasm(
  Uri packageRoot,
  File dest,
  String targetFile,
  String? featuresOverride,
  EngineBuild engineBuild,
) async {
  final webAssets = Directory.fromUri(packageRoot.resolve('web_assets'));
  final existing = File(p.join(webAssets.path, targetFile));

  // web_assets/ holds the DEFAULT build (full features, speed build).
  // Only that combination may read from / write to it; a kept subset or a
  // non-default build is a per-app artifact that must never land there.
  final isDefaultBuild = featuresOverride == null && engineBuild.isDefault;

  // Contributor has locally built WASM — copy directly.
  if (isDefaultBuild && existing.existsSync()) {
    dest.parent.createSync(recursive: true);
    existing.copySync(dest.path);
    return;
  }

  final features =
      featuresOverride ?? BuildConstants.load(packageRoot).wasmFeatures;

  final outDir = isDefaultBuild
      ? webAssets
      : Directory.systemTemp.createTempSync('pdf_manipulator_wasm_');
  try {
    await compileWasmEngine(
      packageRoot: packageRoot,
      features: features,
      outDir: outDir,
      cargoEnv: engineBuild.cargoEnv,
    );

    final built = File(p.join(outDir.path, targetFile));
    if (!built.existsSync()) {
      throw StateError(
        'WASM compiled but $targetFile not found at ${built.path}',
      );
    }
    dest.parent.createSync(recursive: true);
    built.copySync(dest.path);
  } finally {
    if (!isDefaultBuild) {
      outDir.deleteSync(recursive: true);
    }
  }
}

// ── Web: hand-written JS (lane_worker.js) ────────────────────────

Future<void> _copyWebAsset(Uri packageRoot, File dest, String fileName) async {
  final src = File.fromUri(packageRoot.resolve('web_assets/$fileName'));
  if (!src.existsSync()) {
    throw StateError('$fileName not found in web_assets/');
  }
  dest.parent.createSync(recursive: true);
  src.copySync(dest.path);
}

// ══════════════════════════════════════════════════════════════════
// § 5 — CodeConfig mapping
// ══════════════════════════════════════════════════════════════════
