// Build hook for pdf_manipulator.
//
// ═══════════════════════════════════════════════════════════════════
// STRUCTURE
// ═══════════════════════════════════════════════════════════════════
//
//   main()           Flutter hook entry point (native targets only).
//                    Resolves the binary, registers it with Flutter.
//
//   resolveWeb()     Public API for bin/setup.dart (web assets).
//                    Same waterfall, no registration needed — Flutter
//                    serves web/ as static files.
//
//   _resolveNative() Private. Only main() calls this — the correct
//                    cache path and target config only exist inside
//                    the build hook. setup --native delegates to
//                    `flutter build` which triggers main().
//
// ═══════════════════════════════════════════════════════════════════
// RESOLUTION WATERFALL (same for native and web)
// ═══════════════════════════════════════════════════════════════════
//
//   1. CACHED    — existing file, only with a PROOF: hash match, or
//                  no-hash-AND-no-sources (nothing better exists).
//                  When vendor sources are present and there is no
//                  hash, this step always falls through — freshness
//                  is cargo's question, never file-existence.
//   2. DOWNLOAD  — fetch from GitHub Releases; verified against the
//                  pinned hash at download time (or used with a loud
//                  warning when neither hash nor source exists) → cache
//   3. COMPILE   — vendor/pdf_oxide/ exists → cargo/wasm-pack → use it
//   4. SUBMODULE — .gitmodules exists → git init recursive → compile
//   5. ERROR     — nothing worked, clear message with options
//
//   --force skips step 1 (web only, via setup.dart).
//   Version 0.0.0 (dev) skips step 2 (no release exists) — so every
//   dev build lands on step 3 and cargo's fingerprint check decides
//   whether anything actually recompiles (~1s when nothing changed).
//
// ═══════════════════════════════════════════════════════════════════
// USER SCENARIOS
// ═══════════════════════════════════════════════════════════════════
//
//   pub.dev consumer (pdf_manipulator: ^X.Y.Z):
//     Native: automatic via build hook. Downloads prebuilt binary.
//             If binary missing: compiles from vendor source (ships
//             in tarball).
//     Web:    manual `flutter pub run pdf_manipulator:setup`.
//             Same waterfall. Downloads or compiles.
//
//   Git tag consumer (ref: vX.Y.Z):
//     Same as pub.dev — tag has vendor source + release has binaries.
//
//   Git branch consumer (ref: dev, version 0.0.0):
//     Download skipped. Compiles from vendor source or inits
//     submodules first.
//
//   Contributor (path dependency):
//     Same as branch consumer. Always compiles from source.
//
// ═══════════════════════════════════════════════════════════════════
// STALENESS
// ═══════════════════════════════════════════════════════════════════
//
//   Native: fully automatic. Flutter re-runs the hook when
//     pubspec.yaml changes. New assetHashes → hash mismatch →
//     re-downloads.
//
//   Web: NOT automatic. User must run `setup` after package update.
//     Hash check detects stale files and re-resolves automatically.
//     Tracked: dart-lang/native#988 (WasmAsset/JsAsset support).
//
// ═══════════════════════════════════════════════════════════════════
// ASSET HASHES
// ═══════════════════════════════════════════════════════════════════
//
//   Flat Map<String, String> keyed by GitHub Release asset name.
//   Generated by tool/ci/release.sh --update-tag-hashes from:
//     1. GitHub Release API digests (native + WASM build outputs)
//     2. Local SHA-256 of hand-written JS (lane_worker.js)

import 'dart:io';

import 'package:code_assets/code_assets.dart';
import 'package:hooks/hooks.dart';
import 'package:logging/logging.dart';
import 'package:path/path.dart' as p;

import 'package:pdf_manipulator/src/hook/asset_hashes.dart';
import 'package:pdf_manipulator/src/hook/build_constants.dart';
import 'package:pdf_manipulator/src/hook/engine_compiler.dart';
import 'package:pdf_manipulator/src/hook/resolver.dart';
import 'package:pdf_manipulator/src/hook/trim_plan.dart';

final _log = Logger('pdf_manipulator:build');

const _assetId = 'src/ffi/native_bindings.g.dart';

// ══════════════════════════════════════════════════════════════════
// § 1 — Flutter hook entry point (native only)
//
// Called automatically for iOS, Android, macOS, Linux, Windows.
// NOT called for web — web goes through resolveWeb() via setup.dart.
// ══════════════════════════════════════════════════════════════════

void main(List<String> args) async {
  await build(args, (BuildInput input, BuildOutputBuilder output) async {
    if (!input.config.buildCodeAssets) return;

    final constants = BuildConstants.load(input.packageRoot);
    final plan = await resolveTrimPlan(
      trimDefine: input.userDefines['trim'],
      detectorDefine: input.userDefines['trim-detector'],
      defaultFeatures: constants.nativeFeatures,
      // The hooks API exposes no app root; the working directory is the
      // app when the consumer runs `flutter build` from their project.
      appRootCandidate: Directory.current.path,
    );
    if (plan.deferToLink && !input.config.linkingEnabled) {
      stderr.writeln(
        'pdf_manipulator trim-detector record-use: linking is disabled in '
        'this build (debug) — shipping the FULL binary. Release builds '
        'trim in the link hook.',
      );
    }

    final codeConfig = input.config.code;
    final targetTriple = targetTripleFor(codeConfig);
    final linkMode = linkModeFor(codeConfig);
    final libFileName = codeConfig.targetOS.libraryFileName(
      constants.crate,
      linkMode,
    );
    final outFile = File.fromUri(input.outputDirectory.resolve(libFileName));

    // ── Resolve the binary (download, compile, or cache) ──
    await _resolveNative(
      constants: constants,
      plan: plan,
      packageRoot: input.packageRoot,
      version: readVersion(input.packageRoot),
      targetKey: targetKeyFor(codeConfig),
      libFileName: libFileName,
      dest: outFile,
      cacheFile: File.fromUri(
        input.outputDirectoryShared.resolve('$targetTriple/$libFileName'),
      ),
      targetTriple: targetTriple,
      linkMode: linkMode,
      buildInput: input,
    );

    // ── Register with Flutter ──
    _registerCodeAsset(input, output, outFile, linkMode);
    _registerDependencies(input, output);
  });
}

// ══════════════════════════════════════════════════════════════════
// § 2 — Resolution
// ══════════════════════════════════════════════════════════════════

// ── Native (private) ─────────────────────────────────────────────
// Not public because the correct cache path, target triple, link
// mode, and NDK config all come from Flutter's BuildInput — which
// only exists inside the hook. Calling from outside writes to the
// wrong cache. setup --native delegates to `flutter build` instead.
Future<void> _resolveNative({
  required BuildConstants constants,
  required TrimPlan plan,
  required Uri packageRoot,
  required String version,
  required String targetKey,
  required String libFileName,
  required File dest,
  File? cacheFile,
  String? targetTriple,
  LinkMode? linkMode,
  BuildInput? buildInput,
  bool force = false,
}) async {
  final assetName = '$targetKey-$libFileName';

  // A consumer-trimmed feature set has no prebuilt release asset and no
  // pinned hash: version 0.0.0 routes the resolver straight to compile,
  // and cargo's feature-aware fingerprint is the cache.
  final effectiveVersion = plan.isCustom ? '0.0.0' : version;

  await resolveAsset(
    ResolveRequest(
      assetName: assetName,
      downloadUrl: constants.downloadUrl(effectiveVersion, assetName),
      dest: dest,
      cacheFile: plan.isCustom ? null : cacheFile,
      expectedHash: plan.isCustom ? null : assetHashes[assetName],
      version: effectiveVersion,
      packageRoot: packageRoot,
      force: force,
      compile: (File d) async {
        if (buildInput != null && targetTriple != null && linkMode != null) {
          await _compileNativeFromHook(
            buildInput,
            targetTriple,
            linkMode,
            d,
            constants,
            plan,
          );
        } else {
          await _compileNativeFromCli(packageRoot, d, constants, plan);
        }
      },
    ),
  );
}

// ── Web (public — called by bin/setup.dart) ──────────────────────
// Resolves WASM + JS into destDir (typically web/pdf_manipulator/).
// Flutter serves destDir as static files — no registration needed.
//
// Two asset types with different compile fallbacks:
//   WASM build outputs (pdf_oxide_bg.wasm, pdf_oxide.js) → wasm-pack
//   Hand-written JS (lane_worker.js) → copy from package
//
// Returns the number of files freshly resolved (0 = all cached).
Future<int> resolveWeb({
  required Uri packageRoot,
  required String version,
  required Directory destDir,
  bool force = false,
  String? wasmFeaturesOverride,
}) async {
  final constants = BuildConstants.load(packageRoot);
  // A trimmed set has no prebuilt asset, no pinned hash, and must not
  // reuse a default-set artifact: force + version 0.0.0 route the
  // resolver straight to a fresh compile.
  final effectiveVersion = wasmFeaturesOverride == null ? version : '0.0.0';
  final effectiveForce = force || wasmFeaturesOverride != null;

  if (!destDir.existsSync()) {
    destDir.createSync(recursive: true);
  }

  var installed = 0;

  for (final entry in constants.webAssets.entries) {
    final localName = entry.key;
    final assetName = entry.value;
    final dest = File('${destDir.path}/$localName');

    final isWasmBuildOutput = constants.wasmBuildOutputs.contains(localName);

    final fresh = await resolveAsset(
      ResolveRequest(
        assetName: assetName,
        downloadUrl: constants.downloadUrl(effectiveVersion, assetName),
        dest: dest,
        expectedHash: wasmFeaturesOverride == null
            ? assetHashes[assetName]
            : null,
        version: effectiveVersion,
        packageRoot: packageRoot,
        force: effectiveForce,
        compile: isWasmBuildOutput
            ? (File d) =>
                  _compileWasm(packageRoot, d, localName, wasmFeaturesOverride)
            : (File d) => _copyWebAsset(packageRoot, d, localName),
      ),
    );

    if (fresh) installed++;
  }

  return installed;
}

// ══════════════════════════════════════════════════════════════════
// § 3 — Flutter registration (native only)
// ══════════════════════════════════════════════════════════════════

/// Register the native binary as a code asset.
/// Release/AOT routes through hook/link.dart (passthrough today —
/// see hook/link.dart for the tree-shaking roadmap).
void _registerCodeAsset(
  BuildInput input,
  BuildOutputBuilder output,
  File outFile,
  LinkMode linkMode,
) {
  output.assets.code.add(
    CodeAsset(
      package: input.packageName,
      name: _assetId,
      linkMode: linkMode,
      file: outFile.uri,
    ),
    routing: input.config.linkingEnabled
        ? ToLinkHook(input.packageName)
        : const ToAppBundle(),
  );
}

/// Register files Flutter should watch. Any change re-runs the hook;
/// cargo then decides what to actually recompile.
///
/// Must over-approximate cargo's inputs and must exist BEFORE the
/// first build — never derive this list from build outputs like
/// cargo dep-info, or caching goes circular and binaries go stale.
void _registerDependencies(BuildInput input, BuildOutputBuilder output) {
  output.dependencies.add(input.packageRoot.resolve('hook/build.dart'));
  output.dependencies.add(input.packageRoot.resolve('pubspec.yaml'));
  output.dependencies.add(input.packageRoot.resolve('build.json'));

  if (hasVendorSource(input.packageRoot)) {
    for (final crate in const ['vendor/pdf_oxide', 'vendor/office_oxide']) {
      _registerCrateSources(input, output, crate);
    }
  }
}

/// Register one vendored crate's buildable inputs: manifest, lock
/// file, build script, toolchain/flags config, and EVERY file under
/// src/ — not just .rs (include_bytes! assets are inputs too).
void _registerCrateSources(
  BuildInput input,
  BuildOutputBuilder output,
  String crate,
) {
  const configs = [
    'Cargo.toml',
    'Cargo.lock',
    'build.rs',
    'rust-toolchain.toml',
    'rust-toolchain',
    '.cargo/config.toml',
    '.cargo/config',
  ];
  for (final file in configs) {
    final uri = input.packageRoot.resolve('$crate/$file');
    if (File.fromUri(uri).existsSync()) {
      output.dependencies.add(uri);
    }
  }

  final srcDir = Directory.fromUri(input.packageRoot.resolve('$crate/src'));
  if (!srcDir.existsSync()) return;
  var registered = 0;
  for (final entry in srcDir.listSync(recursive: true)) {
    if (entry is File) {
      output.dependencies.add(entry.uri);
      registered++;
    }
  }
  _log.info('registered $registered source files from $crate/src');
}

// ══════════════════════════════════════════════════════════════════
// § 4 — Compile callbacks
// ══════════════════════════════════════════════════════════════════

// ── Native: from build hook (has BuildInput with NDK, triple) ────

Future<void> _compileNativeFromHook(
  BuildInput input,
  String targetTriple,
  LinkMode linkMode,
  File outFile,
  BuildConstants constants,
  TrimPlan plan,
) async {
  final codeConfig = input.config.code;
  await compileEngineForTarget(
    packageRoot: input.packageRoot,
    crateName: constants.crate,
    targetTriple: targetTriple,
    features: plan.features,
    targetDir: p.join(p.fromUri(input.outputDirectory), 'cargo_target'),
    libFileName: codeConfig.targetOS.libraryFileName(constants.crate, linkMode),
    outFile: outFile,
    environment: androidLinkerEnv(codeConfig, targetTriple),
  );
}

// ── Native: from CLI (no BuildInput — uses compile_rust.sh) ──────

Future<void> _compileNativeFromCli(
  Uri packageRoot,
  File dest,
  BuildConstants constants,
  TrimPlan plan,
) async {
  final script = File.fromUri(packageRoot.resolve('tool/compile_rust.sh'));
  if (!script.existsSync()) {
    throw StateError(
      'tool/compile_rust.sh not found. Cannot compile from source.\n'
      'Install from pub.dev or use a git tag with pre-built binaries.',
    );
  }

  final result = await Process.run(
    'bash',
    [script.path, '--native'],
    workingDirectory: p.fromUri(packageRoot),
    environment: {
      ...Platform.environment,
      // The script defaults to build.json's feature set; a trimmed plan
      // must reach this fallback path too, or it silently ships full.
      if (plan.isCustom) 'PDF_FEATURES_NATIVE': plan.features,
    },
  );
  if (result.exitCode != 0) {
    throw StateError(
      'Native compilation failed (exit ${result.exitCode}).\n'
      'stderr: ${result.stderr}\n\n'
      'Ensure Rust is installed: https://rustup.rs',
    );
  }

  final libFileName = _currentLibFileName(constants.crate);
  final compiled = File(
    p.join(
      p.fromUri(packageRoot),
      'vendor/pdf_oxide/target/release',
      libFileName,
    ),
  );
  if (!compiled.existsSync()) {
    throw StateError('Compiled binary not found at ${compiled.path}');
  }
  dest.parent.createSync(recursive: true);
  compiled.copySync(dest.path);
}

// ── Web: WASM build outputs (pdf_oxide.js + pdf_oxide_bg.wasm) ───

Future<void> _compileWasm(
  Uri packageRoot,
  File dest,
  String targetFile,
  String? featuresOverride,
) async {
  final existing = File.fromUri(packageRoot.resolve('web_assets/$targetFile'));

  // Contributor has locally built WASM — copy directly (never for a
  // trimmed set: the local artifact is the default build).
  if (featuresOverride == null && existing.existsSync()) {
    dest.parent.createSync(recursive: true);
    existing.copySync(dest.path);
    return;
  }

  // Compile from source
  final script = File.fromUri(packageRoot.resolve('tool/compile_rust.sh'));
  if (!script.existsSync()) {
    throw StateError(
      'tool/compile_rust.sh not found. Cannot compile WASM.\n'
      'Install from pub.dev or use a git tag with pre-built binaries.',
    );
  }

  final result = await Process.run(
    'bash',
    [script.path, 'wasm'],
    workingDirectory: p.fromUri(packageRoot),
    environment: {
      ...Platform.environment,
      if (featuresOverride != null) 'PDF_FEATURES_WASM': featuresOverride,
    },
  );
  if (result.exitCode != 0) {
    throw StateError(
      'WASM compilation failed (exit ${result.exitCode}).\n'
      'stderr: ${result.stderr}\n\n'
      'Ensure Rust + wasm-pack are installed:\n'
      '  https://rustup.rs\n'
      '  cargo install wasm-pack',
    );
  }

  if (!existing.existsSync()) {
    throw StateError(
      'WASM compiled but $targetFile not found at ${existing.path}',
    );
  }
  dest.parent.createSync(recursive: true);
  existing.copySync(dest.path);
}

// ── Web: hand-written JS (lane_worker.js) ────────────────────────

Future<void> _copyWebAsset(Uri packageRoot, File dest, String fileName) async {
  final src = File.fromUri(packageRoot.resolve('web_assets/$fileName'));
  if (!src.existsSync()) {
    throw StateError('$fileName not found in web_assets/');
  }
  dest.parent.createSync(recursive: true);
  src.copySync(dest.path);
}

// ══════════════════════════════════════════════════════════════════
// § 5 — CodeConfig mapping
// ══════════════════════════════════════════════════════════════════

String _currentLibFileName(String crate) {
  if (Platform.isMacOS) return 'lib$crate.dylib';
  if (Platform.isLinux) return 'lib$crate.so';
  if (Platform.isWindows) return '$crate.dll';
  throw UnsupportedError('Unsupported platform: ${Platform.operatingSystem}');
}
