// Build hook for pdf_manipulator — the single brain for asset resolution.
//
// ═══════════════════════════════════════════════════════════════════
// TWO ROLES, ONE FILE
// ═══════════════════════════════════════════════════════════════════
//
//   1. Flutter hook entry point — called automatically by Flutter's
//      build system for native platforms. Receives BuildInput,
//      resolves the native binary, registers CodeAsset.
//
//   2. Library for bin/setup.dart — exports resolveNative() and
//      resolveWeb() for manual CLI-triggered resolution. setup.dart
//      is a thin wrapper that parses --web/--native/--all and calls
//      these functions.
//
// ═══════════════════════════════════════════════════════════════════
// RESOLUTION WATERFALL (same for native and web)
// ═══════════════════════════════════════════════════════════════════
//
//   1. CACHED   — file exists + SHA-256 matches assetHashes → use it
//   2. DOWNLOAD — fetch from GitHub Releases → cache → use it
//   3. COMPILE  — vendor/pdf_oxide/ exists → cargo/wasm-pack → use it
//   4. SUBMODULE — .gitmodules exists → git init recursive → compile
//   5. ERROR    — nothing worked, clear message with options
//
//   --force skips step 1 (always re-resolves).
//   Version 0.0.0 (dev) skips step 2 (no release exists).
//
// ═══════════════════════════════════════════════════════════════════
// USER SCENARIOS
// ═══════════════════════════════════════════════════════════════════
//
//   pub.dev consumer (pdf_manipulator: ^X.Y.Z):
//     Native: automatic via build hook. Steps 1→2 (download prebuilt).
//             If binary missing from release: step 3 (vendor source
//             ships in tarball, compiles from source).
//     Web:    manual `flutter pub run pdf_manipulator:setup`.
//             Same waterfall. Downloads from release or compiles.
//
//   Git tag consumer (ref: vX.Y.Z):
//     Same as pub.dev — tag has vendor source + release has binaries.
//
//   Git branch consumer (ref: dev, version 0.0.0):
//     Download skipped (no release). Compiles from vendor source.
//     If not cloned with --recursive: submodule init first.
//
//   Contributor (path dependency):
//     Same as branch consumer. Always compiles from source.
//
// ═══════════════════════════════════════════════════════════════════
// STALENESS
// ═══════════════════════════════════════════════════════════════════
//
//   Native: fully automatic. Flutter re-runs the build hook when
//     pubspec.yaml changes (registered as dependency). Package
//     update → new assetHashes → cached binary hash mismatch →
//     re-downloads. User never thinks about it.
//
//   Web: NOT automatic. User must run `setup` after package update.
//     The setup script hash-checks every installed file against
//     assetHashes and re-resolves any mismatches. If user forgets,
//     stale assets stay until the next setup run.
//     This is a Flutter limitation — no build hook for web assets.
//     Tracked: dart-lang/native#2829 (DataAsset support).
//
//   When --force is passed: cache check skipped entirely,
//     everything re-resolved from download or compile.
//
//   When no hash is available (dev version, or missing entry):
//     Published versions: warning logged, cached file used anyway.
//     Dev version (0.0.0): cached file used silently (just compiled).
//
// ═══════════════════════════════════════════════════════════════════
// WEB SUPPORT
// ═══════════════════════════════════════════════════════════════════
//
//   resolveWeb() is fully implemented. It resolves all 4 web assets:
//     pdf_oxide_bg.wasm — WASM binary (compiled by wasm-pack)
//     pdf_oxide.js      — JS glue (compiled by wasm-pack)
//     coordinator.js    — worker pool manager (hand-written)
//     worker.js         — WASM worker (hand-written)
//
//   WASM build outputs (wasm + js glue) are always resolved together
//   from the same source — both downloaded from the same release, or
//   both compiled from the same wasm-pack run. Never mix versions.
//
//   Hand-written JS files fall back to copying from the package's
//   web_assets/ directory if download fails (they always ship).
//
//   When Flutter adds DataAsset support, main() adds one call to
//   resolveWeb() and setup.dart becomes optional. Zero new code.
//
// ═══════════════════════════════════════════════════════════════════
// ASSET HASHES
// ═══════════════════════════════════════════════════════════════════
//
//   assetHashes is a flat Map<String, String> keyed by GitHub Release
//   asset name (e.g. 'macos-arm64-libpdf_oxide.dylib',
//   'wasm-pdf_oxide_bg.wasm'). Generated by tool/release.sh
//   --update-tag-hashes at release time from two sources:
//     1. GitHub Release API digests (native + WASM build outputs)
//     2. Local SHA-256 of hand-written JS (coordinator.js, worker.js)
//
//   The resolver uses these to verify cached files and detect stale
//   assets after a package update.

import 'dart:io';

import 'package:code_assets/code_assets.dart';
import 'package:hooks/hooks.dart';
import 'package:logging/logging.dart';
import 'package:path/path.dart' as p;

import 'package:pdf_manipulator/src/hook/asset_hashes.dart';
import 'package:pdf_manipulator/src/hook/resolver.dart';

final _log = Logger('pdf_manipulator:build');

const _assetId = 'src/ffi/native_bindings.g.dart';
const _crateName = 'pdf_oxide';
const _featuresFallback =
    'icc,legacy-crypto,rendering,signatures,native-bridge';

// Web assets — GitHub Release asset names. Keyed by local filename.
const webAssets = {
  'pdf_oxide_bg.wasm': 'wasm-pdf_oxide_bg.wasm',
  'pdf_oxide.js': 'wasm-pdf_oxide.js',
  'coordinator.js': 'wasm-coordinator.js',
  'worker.js': 'wasm-worker.js',
};

// ══════════════════════════════════════════════════════════════════
// Flutter hook entry point
// ══════════════════════════════════════════════════════════════════

void main(List<String> args) async {
  await build(args, (BuildInput input, BuildOutputBuilder output) async {
    if (!input.config.buildCodeAssets) return;

    final codeConfig = input.config.code;
    final targetTriple = _targetTriple(codeConfig);
    final linkMode = _linkMode(codeConfig);
    final libFileName =
        codeConfig.targetOS.libraryFileName(_crateName, linkMode);
    final outFile =
        File.fromUri(input.outputDirectory.resolve(libFileName));
    final platform = _platformKey(codeConfig);
    final version = readVersion(input.packageRoot);

    await resolveNative(
      packageRoot: input.packageRoot,
      version: version,
      platform: platform,
      libFileName: libFileName,
      dest: outFile,
      cacheFile: File.fromUri(
        input.outputDirectoryShared.resolve(libFileName),
      ),
      targetTriple: targetTriple,
      linkMode: linkMode,
      buildInput: input,
    );

    output.assets.code.add(
      CodeAsset(
        package: input.packageName,
        name: _assetId,
        linkMode: linkMode,
        file: outFile.uri,
      ),
      routing: input.config.linkingEnabled
          ? ToLinkHook(input.packageName)
          : const ToAppBundle(),
    );
    output.dependencies.add(input.packageRoot.resolve('hook/build.dart'));
    output.dependencies.add(input.packageRoot.resolve('pubspec.yaml'));
    output.dependencies.add(
      input.packageRoot.resolve('vendor/pdf_oxide/Cargo.toml'),
    );

    if (hasVendorSource(input.packageRoot)) {
      final targetDir =
          p.join(p.fromUri(input.outputDirectory), 'cargo_target');
      final depInfoPath = p.join(
        targetDir, targetTriple, 'release', 'deps', 'pdf_oxide.d',
      );
      _registerCargoDeps(output, depInfoPath, input.packageRoot);
    }
  });
}

// ══════════════════════════════════════════════════════════════════
// Public API — called by both main() above and bin/setup.dart
// ══════════════════════════════════════════════════════════════════

/// Resolve the native binary for one platform.
///
/// [buildInput] is only needed when called from the Flutter hook
/// (provides NDK compiler info for Android). Null when called from
/// setup.dart.
Future<void> resolveNative({
  required Uri packageRoot,
  required String version,
  required String platform,
  required String libFileName,
  required File dest,
  File? cacheFile,
  String? targetTriple,
  LinkMode? linkMode,
  BuildInput? buildInput,
  bool force = false,
}) async {
  final assetName = '$platform-$libFileName';

  await resolveAsset(ResolveRequest(
    assetName: assetName,
    dest: dest,
    cacheFile: cacheFile,
    expectedHash: assetHashes[assetName],
    version: version,
    packageRoot: packageRoot,
    force: force,
    compile: (File d) async {
      if (buildInput != null && targetTriple != null && linkMode != null) {
        await _compileNativeFromHook(
            buildInput, targetTriple, linkMode, d);
      } else {
        await _compileNativeFromCli(packageRoot, d);
      }
    },
  ));
}

/// Resolve all web assets into [destDir].
///
/// Returns the number of files installed (0 if all up to date).
Future<int> resolveWeb({
  required Uri packageRoot,
  required String version,
  required Directory destDir,
  bool force = false,
}) async {
  if (!destDir.existsSync()) {
    destDir.createSync(recursive: true);
  }

  var installed = 0;

  for (final entry in webAssets.entries) {
    final localName = entry.key;
    final assetName = entry.value;
    final dest = File('${destDir.path}/$localName');

    final isWasmBuildOutput =
        localName == 'pdf_oxide_bg.wasm' || localName == 'pdf_oxide.js';

    final fresh = await resolveAsset(ResolveRequest(
      assetName: assetName,
      dest: dest,
      expectedHash: assetHashes[assetName],
      version: version,
      packageRoot: packageRoot,
      force: force,
      compile: isWasmBuildOutput
          ? (File d) => _compileWasm(packageRoot, d, localName)
          : (File d) => _copyWebAsset(packageRoot, d, localName),
    ));

    if (fresh) installed++;
  }

  return installed;
}

// ══════════════════════════════════════════════════════════════════
// Compile callbacks
// ══════════════════════════════════════════════════════════════════

/// Compile native from the Flutter build hook (has BuildInput with
/// NDK info, target triple, link mode).
Future<void> _compileNativeFromHook(
  BuildInput input,
  String targetTriple,
  LinkMode linkMode,
  File outFile,
) async {
  final manifestPath = p.fromUri(
    input.packageRoot.resolve('vendor/pdf_oxide/Cargo.toml'),
  );
  final targetDir =
      p.join(p.fromUri(input.outputDirectory), 'cargo_target');

  _log.info('compiling from source for $targetTriple');

  final env = <String, String>{};
  final codeConfig = input.config.code;

  if (codeConfig.targetOS == OS.android) {
    final cc = codeConfig.cCompiler;
    if (cc != null) {
      final compilerDir = p.dirname(p.fromUri(cc.compiler));
      final ndkTriple = targetTriple == 'armv7-linux-androideabi'
          ? 'armv7a-linux-androideabi'
          : targetTriple;
      // The NDK per-API clang driver is a `.cmd` batch wrapper on Windows
      // hosts (e.g. aarch64-linux-android21-clang.cmd); passing the bare name
      // makes cargo fail with "could not exec the linker ... program not
      // found". Append the host executable extension so Android cross-compiles
      // link from a Windows host as well as Linux/macOS. Platform.isWindows
      // here is the BUILD host (which runs cargo), not the Android target.
      final clangExt = Platform.isWindows ? '.cmd' : '';
      final linker = p.join(compilerDir, '${ndkTriple}21-clang$clangExt');
      final ar = p.join(compilerDir, 'llvm-ar');
      final envKey =
          'CARGO_TARGET_${targetTriple.toUpperCase().replaceAll('-', '_')}';
      env['${envKey}_LINKER'] = linker;
      env['${envKey}_AR'] = ar;
      _log.info('NDK linker: $linker');
    }
  }

  if (Platform.isMacOS) {
    env['PATH'] = Platform.environment['PATH']!
        .split(':')
        .where((e) => !e.contains('Contents/Developer/'))
        .join(':');
  }

  final result = await Process.run(
    'cargo',
    [
      'build',
      '--manifest-path', manifestPath,
      '--lib',
      '--release',
      '--target', targetTriple,
      '--target-dir', targetDir,
      '--features', _resolveFeatures(input.packageRoot),
    ],
    environment: {...Platform.environment, ...env},
  );

  if (result.exitCode != 0) {
    throw StateError(
      'cargo build failed (exit ${result.exitCode}).\n'
      'stderr: ${result.stderr}\n\n'
      'Ensure Rust is installed: https://rustup.rs\n'
      'Then: rustup target add $targetTriple',
    );
  }

  final compiled = p.join(
    targetDir,
    targetTriple,
    'release',
    codeConfig.targetOS
        .libraryFileName(_crateName, linkMode)
        .replaceAll('-', '_'),
  );

  if (!File(compiled).existsSync()) {
    throw StateError('Compiled library not found at $compiled.');
  }

  outFile.parent.createSync(recursive: true);
  File(compiled).copySync(outFile.path);
  _log.info('compiled → ${outFile.path}');
}

/// Compile native from CLI (no BuildInput — uses compile_rust.sh).
Future<void> _compileNativeFromCli(Uri packageRoot, File dest) async {
  final script =
      File.fromUri(packageRoot.resolve('tool/compile_rust.sh'));
  if (!script.existsSync()) {
    throw StateError(
      'tool/compile_rust.sh not found. Cannot compile from source.\n'
      'Install from pub.dev or use a git tag with pre-built binaries.',
    );
  }

  final result = await Process.run(
    'bash',
    [script.path, '--native'],
    workingDirectory: p.fromUri(packageRoot),
  );
  if (result.exitCode != 0) {
    throw StateError(
      'Native compilation failed (exit ${result.exitCode}).\n'
      'stderr: ${result.stderr}\n\n'
      'Ensure Rust is installed: https://rustup.rs',
    );
  }

  final libFileName = currentLibFileName();
  final compiled = File(p.join(
    p.fromUri(packageRoot),
    'vendor/pdf_oxide/target/release',
    libFileName,
  ));
  if (!compiled.existsSync()) {
    throw StateError('Compiled binary not found at ${compiled.path}');
  }
  dest.parent.createSync(recursive: true);
  compiled.copySync(dest.path);
}

/// Compile WASM outputs (pdf_oxide.js + pdf_oxide_bg.wasm).
Future<void> _compileWasm(
    Uri packageRoot, File dest, String targetFile) async {
  final existing =
      File.fromUri(packageRoot.resolve('web_assets/$targetFile'));

  if (existing.existsSync()) {
    dest.parent.createSync(recursive: true);
    existing.copySync(dest.path);
    return;
  }

  final script =
      File.fromUri(packageRoot.resolve('tool/compile_rust.sh'));
  if (!script.existsSync()) {
    throw StateError(
      'tool/compile_rust.sh not found. Cannot compile WASM.\n'
      'Install from pub.dev or use a git tag with pre-built binaries.',
    );
  }

  final result = await Process.run(
    'bash',
    [script.path, '--wasm'],
    workingDirectory: p.fromUri(packageRoot),
  );
  if (result.exitCode != 0) {
    throw StateError(
      'WASM compilation failed (exit ${result.exitCode}).\n'
      'stderr: ${result.stderr}\n\n'
      'Ensure Rust + wasm-pack are installed:\n'
      '  https://rustup.rs\n'
      '  cargo install wasm-pack',
    );
  }

  if (!existing.existsSync()) {
    throw StateError(
        'WASM compiled but $targetFile not found at ${existing.path}');
  }
  dest.parent.createSync(recursive: true);
  existing.copySync(dest.path);
}

/// Copy hand-written JS from package web_assets/.
Future<void> _copyWebAsset(
    Uri packageRoot, File dest, String fileName) async {
  final src = File.fromUri(packageRoot.resolve('web_assets/$fileName'));
  if (!src.existsSync()) {
    throw StateError('$fileName not found in web_assets/');
  }
  dest.parent.createSync(recursive: true);
  src.copySync(dest.path);
}

// ══════════════════════════════════════════════════════════════════
// Platform detection — used by both hook and setup.dart
// ══════════════════════════════════════════════════════════════════

/// Platform key for the current machine.
String currentPlatformKey() {
  if (Platform.isMacOS) return _isArm64() ? 'macos-arm64' : 'macos-x64';
  if (Platform.isLinux) return _isArm64() ? 'linux-arm64' : 'linux-x64';
  if (Platform.isWindows) {
    return _isArm64() ? 'windows-arm64' : 'windows-x64';
  }
  throw UnsupportedError(
      'Unsupported platform: ${Platform.operatingSystem}');
}

/// Library filename for the current platform.
String currentLibFileName() {
  if (Platform.isMacOS) return 'lib$_crateName.dylib';
  if (Platform.isLinux) return 'lib$_crateName.so';
  if (Platform.isWindows) return '$_crateName.dll';
  throw UnsupportedError(
      'Unsupported platform: ${Platform.operatingSystem}');
}

bool _isArm64() {
  if (Platform.isWindows) {
    return Platform.environment['PROCESSOR_ARCHITECTURE'] == 'ARM64';
  }
  final result = Process.runSync('uname', ['-m']);
  final arch = (result.stdout as String).trim();
  return arch == 'arm64' || arch == 'aarch64';
}

// ══════════════════════════════════════════════════════════════════
// Internal helpers
// ══════════════════════════════════════════════════════════════════

String _resolveFeatures(Uri packageRoot) {
  final script =
      File.fromUri(packageRoot.resolve('tool/compile_rust.sh'));
  if (script.existsSync()) {
    final result =
        Process.runSync('bash', [script.path, '--features', 'native']);
    if (result.exitCode == 0) {
      final features = (result.stdout as String).trim();
      if (features.isNotEmpty) return features;
    }
  }
  return _featuresFallback;
}

LinkMode _linkMode(CodeConfig code) {
  return switch (code.linkModePreference) {
    LinkModePreference.dynamic ||
    LinkModePreference.preferDynamic =>
      DynamicLoadingBundled(),
    LinkModePreference.static ||
    LinkModePreference.preferStatic =>
      StaticLinking(),
    _ => DynamicLoadingBundled(),
  };
}

String _targetTriple(CodeConfig code) {
  if (code.targetOS == OS.iOS &&
      code.targetArchitecture == Architecture.arm64 &&
      code.iOS.targetSdk == IOSSdk.iPhoneSimulator) {
    return 'aarch64-apple-ios-sim';
  }
  return switch ((code.targetOS, code.targetArchitecture)) {
    (OS.android, Architecture.arm) => 'armv7-linux-androideabi',
    (OS.android, Architecture.arm64) => 'aarch64-linux-android',
    (OS.android, Architecture.ia32) => 'i686-linux-android',
    (OS.android, Architecture.x64) => 'x86_64-linux-android',
    (OS.iOS, Architecture.arm64) => 'aarch64-apple-ios',
    (OS.iOS, Architecture.x64) => 'x86_64-apple-ios',
    (OS.linux, Architecture.arm64) => 'aarch64-unknown-linux-gnu',
    (OS.linux, Architecture.x64) => 'x86_64-unknown-linux-gnu',
    (OS.macOS, Architecture.arm64) => 'aarch64-apple-darwin',
    (OS.macOS, Architecture.x64) => 'x86_64-apple-darwin',
    (OS.windows, Architecture.arm64) => 'aarch64-pc-windows-msvc',
    (OS.windows, Architecture.x64) => 'x86_64-pc-windows-msvc',
    (_, _) => throw UnsupportedError(
        'Unsupported: ${code.targetOS} ${code.targetArchitecture}'),
  };
}

String _platformKey(CodeConfig code) {
  if (code.targetOS == OS.iOS &&
      code.targetArchitecture == Architecture.arm64 &&
      code.iOS.targetSdk == IOSSdk.iPhoneSimulator) {
    return 'ios-sim-arm64';
  }
  return switch ((code.targetOS, code.targetArchitecture)) {
    (OS.android, Architecture.arm) => 'android-arm',
    (OS.android, Architecture.arm64) => 'android-arm64',
    (OS.android, Architecture.ia32) => 'android-x86',
    (OS.android, Architecture.x64) => 'android-x64',
    (OS.iOS, Architecture.arm64) => 'ios-arm64',
    (OS.iOS, Architecture.x64) => 'ios-sim-x64',
    (OS.linux, Architecture.arm64) => 'linux-arm64',
    (OS.linux, Architecture.x64) => 'linux-x64',
    (OS.macOS, Architecture.arm64) => 'macos-arm64',
    (OS.macOS, Architecture.x64) => 'macos-x64',
    (OS.windows, Architecture.arm64) => 'windows-arm64',
    (OS.windows, Architecture.x64) => 'windows-x64',
    (_, _) => throw UnsupportedError(
        'Unsupported: ${code.targetOS} ${code.targetArchitecture}'),
  };
}

void _registerCargoDeps(
  BuildOutputBuilder output,
  String depInfoPath,
  Uri packageRoot,
) {
  final depFile = File(depInfoPath);
  if (!depFile.existsSync()) {
    _log.warning('dep-info not found at $depInfoPath');
    return;
  }

  final content = depFile.readAsStringSync();
  final crateRoot =
      p.fromUri(packageRoot.resolve('vendor/pdf_oxide/'));
  final packageDir = p.fromUri(packageRoot);
  var registered = 0;

  for (final line in content.split('\n')) {
    final trimmed = line.trim();
    if (trimmed.isEmpty || trimmed.startsWith('#')) continue;

    final colonIdx = trimmed.indexOf(':');
    if (colonIdx < 0) continue;
    final deps = trimmed.substring(colonIdx + 1).trim();

    if (deps.isEmpty) {
      final candidate = trimmed.substring(0, colonIdx).trim();
      if (candidate.isNotEmpty) {
        _addDep(output, packageDir, crateRoot, candidate);
        registered++;
      }
      continue;
    }

    for (final dep in deps.split(' ')) {
      final d = dep.trim();
      if (d.isNotEmpty) {
        _addDep(output, packageDir, crateRoot, d);
        registered++;
      }
    }
  }

  _log.info('registered $registered source deps from Cargo dep-info');
}

void _addDep(
  BuildOutputBuilder output,
  String packageDir,
  String crateRoot,
  String depPath,
) {
  final absolute = p.isAbsolute(depPath)
      ? depPath
      : p.normalize(p.join(crateRoot, depPath));

  if (!File(absolute).existsSync()) return;
  if (!p.isWithin(packageDir, absolute)) return;

  output.dependencies.add(Uri.file(absolute));
}
