/// SHA-256 hashes of release assets, keyed by GitHub Release asset name.
///
/// The build hook and web setup verify downloaded files against these.
/// Generated by tool/release.sh --update-tag-hashes.
const Map<String, String> assetHashes = {
  // --- GENERATED HASHES START ---
  'android-arm-libpdf_oxide.so': 'dbc558879c6c44d8fed6bd60b128d556a54c228c24b6be86c6e02e73590a4451',
  'android-arm64-libpdf_oxide.so': 'bc7fa522fab0c7eab61779353a6b812f734b3d5f84cd7c1f81e823aa39bf2bf8',
  'android-x64-libpdf_oxide.so': '6ee42a88654d063e7c21f4e2d4b11355b55429d272a7c7c4090e2db99e86bc42',
  'android-x86-libpdf_oxide.so': 'e5177370c135273254eaa5da891a2eccb835f1f66d5db86023bc365832cdfc1e',
  'ios-arm64-libpdf_oxide.a': 'd5799bf79397915a02ef32c6d507c30e6f7a81d74e0bb9515eb5c9261f8d6ae6',
  'ios-sim-arm64-libpdf_oxide.a': 'd280418cdc8db11c498a4d04f8e65d92e5b948884d805b4f23f305b85335ea83',
  'ios-sim-x64-libpdf_oxide.a': 'f9280e825f2181dd5821ed2a4cdcdab715cd165cc81d92bc5534f95817c3b325',
  'linux-arm64-libpdf_oxide.so': '965696159a63a94f915a108fcab8a816f11f19710542f959d1d6ba725f8de7f8',
  'linux-x64-libpdf_oxide.so': 'df42eeb57d6898d8a6e4c68f0b5466e1c9a71e08154555aaffebed52408048fe',
  'macos-arm64-libpdf_oxide.dylib': 'e3ca8a8fa8cdb556f4988e2a3cba805ccb0aa50070aa7224d8e2f8101398e104',
  'macos-x64-libpdf_oxide.dylib': '67966bb171e77672fa29e031f1677880896a4ef5b63dbf68e85c2b90cf2e0958',
  'wasm-pdf_oxide.js': 'f9de751206a1c9a299bf7e81335db9f8dcc37d13d0a930c275731901387f7380',
  'wasm-pdf_oxide_bg.wasm': 'db8a59e4867f9d51ac162947f44d32b8550a809d5136f691fcfdb7c03e35b4b2',
  'windows-arm64-pdf_oxide.dll': '0c4820c4b56d5b7f5e47dd7cfa08ddf57649f799134729a910e29beed5adff42',
  'windows-x64-pdf_oxide.dll': '1f74c4624a7798d5247284a58f62ff369c1e798566586ee0002904b899c5aebc',
  'wasm-lane_worker.js': 'c103fa8e99822ae518a325a0662f17f0737b5928d5ca88fc107d53c711e13362',
  // --- GENERATED HASHES END ---
};
