/// SHA-256 hashes of release assets, keyed by GitHub Release asset name.
///
/// The build hook and web setup verify downloaded files against these.
/// Generated by tool/ci/release.sh --update-tag-hashes.
const Map<String, String> assetHashes = {
  // --- GENERATED HASHES START ---
  'android-arm-libpdf_oxide.so': '2c98b7bb1887576c3c155606b9e5de9da82d24a9b5631d9a45c1f94f3dfaf4c8',
  'android-arm64-libpdf_oxide.so': 'e0fc584def80e116e596fc829883b39c702d9c15f4cce6e712c55c0d3aab5d6e',
  'android-x64-libpdf_oxide.so': 'a673d51e0c8ebefbe07822185f193a410ebc07ecd809d32d963908c7a5b6c9c1',
  'android-x86-libpdf_oxide.so': 'f07db527edaf5af4d0f36439b1ebcee6a9068151324201269e7cf2ac600a003f',
  'ios-arm64-libpdf_oxide.a': '8e897fb4832209ed65a8a091033e04bf6b501696e81c8b1424977536927d3dbc',
  'ios-sim-arm64-libpdf_oxide.a': 'b62525b7cbedd2ab54b4d2f3b304687e8306948eccd304452853ab79d4cc5284',
  'ios-sim-x64-libpdf_oxide.a': '2a5c602b9ec06b6b7bef95848d5786de69c42d16dc024182823d12c4f774cbb6',
  'linux-arm64-libpdf_oxide.so': '40b5f86bb3db76f879ee1c5a1e07b2bfb85c5b8a10692509b5a14654568fcab7',
  'linux-x64-libpdf_oxide.so': 'b96d64b2d67bc03b34130528a83c8e15bcb799550a61a5d1d5c99a04ea038631',
  'macos-arm64-libpdf_oxide.dylib': '0fc16c75437707ebcdd063dfccb006a068a97272fe472470921b78dfaa41d4ef',
  'macos-x64-libpdf_oxide.dylib': 'f9312057fa170cc2ba6df19372436bcab2e74d3fcc2e45102eb0e76458c441d9',
  'wasm-pdf_oxide.js': '9c6500a0506b08d1cc827037a3f68a4448385609eb4905902afcfdf6efbd9f4c',
  'wasm-pdf_oxide_bg.wasm': 'f685f8affc9d337cd54449c68b2b495c2a2b2f046cf429d2143b6bd83917aeae',
  'windows-arm64-pdf_oxide.dll': 'e970da57dd0ab7ed19f6db47313b07bb3d25b3b590068e785fa63982315bfa38',
  'windows-x64-pdf_oxide.dll': '4cacb88a7838da1c15285ea1b20551aefd9b0809874efc8b7e2a48bb4f6f0619',
  'wasm-lane_worker.js': '0c0bc8be42c9d3882a12117562c2df3707f89a92c9f4f54d04bb57a7c2329586',
  // --- GENERATED HASHES END ---
};
