/// SHA-256 hashes of release assets, keyed by GitHub Release asset name.
///
/// The build hook and web setup verify downloaded files against these.
/// Generated by tool/ci/release.sh --update-tag-hashes.
const Map<String, String> assetHashes = {
  // --- GENERATED HASHES START ---
  'android-arm-libpdf_oxide.so': '2c98b7bb1887576c3c155606b9e5de9da82d24a9b5631d9a45c1f94f3dfaf4c8',
  'android-arm64-libpdf_oxide.so': 'e0fc584def80e116e596fc829883b39c702d9c15f4cce6e712c55c0d3aab5d6e',
  'android-x64-libpdf_oxide.so': 'b8db6c175b51690bb905d46911bf07e8e15bc132702cc7ebb95554e4b6441f1e',
  'android-x86-libpdf_oxide.so': 'f07db527edaf5af4d0f36439b1ebcee6a9068151324201269e7cf2ac600a003f',
  'ios-arm64-libpdf_oxide.a': '2e4bbaf116a5e35a80bf514bd52447e0aca225ae3fde461153b314b3420d1c50',
  'ios-sim-arm64-libpdf_oxide.a': '3eabb2acc1ae52fe6d7739c430e208eaced17ea53a2b09a07b88e7feac019052',
  'ios-sim-x64-libpdf_oxide.a': 'c071a3cbdc669744d54e02dcf1eea9b0dd3636b12deeb52188b378280f6e11d8',
  'linux-arm64-libpdf_oxide.so': '40b5f86bb3db76f879ee1c5a1e07b2bfb85c5b8a10692509b5a14654568fcab7',
  'linux-x64-libpdf_oxide.so': '554f0ad6109cecabf9ec609443a08aaef9bfe0fa7fac26c22d2f32420b2a4b94',
  'macos-arm64-libpdf_oxide.dylib': '0fc16c75437707ebcdd063dfccb006a068a97272fe472470921b78dfaa41d4ef',
  'macos-x64-libpdf_oxide.dylib': '7212699ea746d4112d1db3f6083bea108192fa6c6d4e6ee0bdffd95bdd5f2e81',
  'wasm-pdf_oxide.js': '2a83dcf1224cadabe12f579b9c79bff8eb6ce8441d6d04a28c4614b309f7beef',
  'wasm-pdf_oxide_bg.wasm': 'f5f9ff26008d149b5430b9edfbaefffa4c04e14322f60750028475567f78ff39',
  'windows-arm64-pdf_oxide.dll': '85975a24d68b3b5faac4cdf3aa134af9c582fd13e79c1fdec5e056bf79d8691d',
  'windows-x64-pdf_oxide.dll': '83f136fc59b555850257ef1b4f61460c70fe0194d88b4f189a278b7d0c274d8d',
  'wasm-lane_worker.js': '0c0bc8be42c9d3882a12117562c2df3707f89a92c9f4f54d04bb57a7c2329586',
  // --- GENERATED HASHES END ---
};
