name: CocoaPods Cache
description: Cache CocoaPods for iOS builds.

runs:
  using: composite
  steps:
    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: example/ios/Pods
        key: pods-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('example/ios/Podfile') }}
        restore-keys: pods-${{ runner.os }}-${{ runner.arch }}-
