name: CocoaPods Cache
description: Cache CocoaPods for iOS builds.

runs:
  using: composite
  steps:
    - uses: actions/cache@v5
      with:
        path: example/ios/Pods
        key: pods-${{ hashFiles('example/ios/Podfile') }}
        restore-keys: pods-
