name: Integration Test (Linux)
description: Run example Flutter integration test on Linux desktop via Makefile

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-fvm
    - uses: ./.github/actions/setup-rust
    - shell: bash
      run: sudo apt-get update -qq && sudo apt-get install -y -qq xvfb
    - shell: bash
      run: xvfb-run make test-example-linux
