// FixtureGenerator — emits the test fixture catalog as Dart source.
//
// Run via `make fixtures` (test targets depend on it). Flow:
//
//   1. Hash the generator's INPUTS (this file, the catalog, the photo
//      asset). If test/fixtures/generated/.stamp matches → fresh, exit.
//      File existence is never proof; the stamp is (same rule as the
//      binary resolver).
//   2. Otherwise wipe generated/, build every FixtureSpec with
//      dart-pdf, and emit one Dart file per fixture: bytes as a base64
//      constant + the spec's declared truths as a const record. Tests
//      import these files — no dart:io ever runs inside a test, and VM
//      and browser consume identical bytes through identical code.
//
// This is a dev tool: dart:io is at home here, never in tests.

import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

import '../test/fixtures/catalog.dart';

const _generatedDir = 'test/fixtures/generated';

final _inputs = [
  'tool/generate_fixtures.dart',
  'test/fixtures/catalog.dart',
  'test/harness/photo_png.dart',
];

Future<void> main() async {
  final stamp = _stampInputs();
  final stampFile = File('$_generatedDir/.stamp');
  if (stampFile.existsSync() && stampFile.readAsStringSync() == stamp) {
    stdout.writeln('fixtures: fresh (${catalog.length} specs, stamp match)');
    return;
  }

  final dir = Directory(_generatedDir);
  if (dir.existsSync()) dir.deleteSync(recursive: true);
  dir.createSync(recursive: true);

  final exports = <String>[];
  for (final spec in catalog) {
    final sw = Stopwatch()..start();
    final bytes = await spec.build();
    final file = 'f_${spec.name}.dart';
    File('$_generatedDir/$file').writeAsStringSync(_emit(spec, bytes));
    exports.add("export '$file';");
    stdout.writeln(
      'fixtures: ${spec.name} — ${bytes.length} bytes in ${sw.elapsedMilliseconds}ms',
    );
  }

  File('$_generatedDir/fixtures.dart').writeAsStringSync('''
// GENERATED by tool/generate_fixtures.dart — do not edit.
// One import gives every generated fixture + its declared truths.

${exports.join('\n')}
''');
  // Canonicalize: emitted spacing must survive `dart format` untouched,
  // or every regeneration re-dirties the tree under the format gate.
  final fmt = Process.runSync(Platform.resolvedExecutable, [
    'format',
    _generatedDir,
  ]);
  if (fmt.exitCode != 0) {
    stderr.write(fmt.stderr);
    exitCode = fmt.exitCode;
    return;
  }

  stampFile.writeAsStringSync(stamp);
  stdout.writeln('fixtures: generated ${catalog.length} fixtures');
}

String _stampInputs() {
  final bytes = <int>[];
  for (final path in _inputs) {
    bytes.addAll(File(path).readAsBytesSync());
  }
  return sha256.convert(bytes).toString();
}

String _emit(FixtureSpec spec, List<int> bytes) {
  final ident = _camel(spec.name);
  final b64 = base64Encode(bytes);
  final chunks = <String>[
    for (var i = 0; i < b64.length; i += 76)
      "    '${b64.substring(i, (i + 76).clamp(0, b64.length))}'",
  ];
  final why = _wrapComment(spec.why);
  return '''
// GENERATED by tool/generate_fixtures.dart — do not edit.
// Regenerate: make fixtures
//
$why

import 'dart:convert';
import 'dart:typed_data';

/// dart-pdf-produced fixture bytes (decoded once at first use).
final Uint8List f$ident = base64Decode(_b64);

/// Declared ground truth — tests assert against THIS, never against
/// re-derived engine output.
const f${ident}Truth = (
${spec.truths.entries.map((e) => '  ${e.key}: ${_literal(e.value)},').join('\n')}
);

const _b64 =
${chunks.join('\n')};
''';
}

/// Word-wrap [text] into `// `-prefixed lines of at most 70 columns.
String _wrapComment(String text) {
  final lines = <String>[];
  var line = StringBuffer();
  for (final word in text.split(RegExp(r'\s+'))) {
    if (line.isNotEmpty && line.length + 1 + word.length > 67) {
      lines.add('// $line');
      line = StringBuffer();
    }
    if (line.isNotEmpty) line.write(' ');
    line.write(word);
  }
  if (line.isNotEmpty) lines.add('// $line');
  return lines.join('\n');
}

String _camel(String snake) =>
    snake.split('_').map((w) => w[0].toUpperCase() + w.substring(1)).join();

String _literal(Object v) => switch (v) {
  final String s => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'",
  final List<Object> l => '[${l.map(_literal).join(', ')}]',
  _ => '$v', // int, double, bool
};
