// FixtureGenerator — emits the test fixture catalog as Dart source.
//
// Run via `make fixtures` (test targets depend on it). Flow:
//
//   1. Hash the generator's INPUTS (this file, the catalog, the photo
//      asset). If test/fixtures/generated/.stamp matches → fresh, exit.
//      File existence is never proof; the stamp is (same rule as the
//      binary resolver).
//   2. Otherwise wipe generated/, build every FixtureSpec with
//      dart-pdf, and emit one Dart file per fixture: bytes as a base64
//      constant + the spec's declared truths as a const record. Tests
//      import these files — no dart:io ever runs inside a test, and VM
//      and browser consume identical bytes through identical code.
//
// This is a dev tool: dart:io is at home here, never in tests.

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';

import '../test/fixtures/catalog.dart';

const _generatedDir = 'test/fixtures/generated';

final _inputs = ['tool/generate_fixtures.dart', 'test/fixtures/catalog.dart'];

Future<void> main() async {
  final stamp = _stampInputs();
  final stampFile = File('$_generatedDir/.stamp');
  if (stampFile.existsSync() && stampFile.readAsStringSync() == stamp) {
    stdout.writeln('fixtures: fresh (${catalog.length} specs, stamp match)');
    return;
  }

  final dir = Directory(_generatedDir);
  if (dir.existsSync()) dir.deleteSync(recursive: true);
  dir.createSync(recursive: true);

  final exports = <String>[];

  // The photo-like raster the image batteries feed into dart-pdf.
  // Built once here, emitted as a generated fixture (never committed),
  // and injected into every spec's build() so the catalog needs no
  // raster of its own.
  final photoPng = buildPhotoPng();
  File(
    '$_generatedDir/f_photo_png.dart',
  ).writeAsStringSync(_emitBytes('photoPng', photoPng));
  exports.add("export 'f_photo_png.dart';");

  // The transparent raster the image-stamp transparency test feeds in.
  final transparentPng = buildTransparentPng();
  File('$_generatedDir/f_transparent_png.dart').writeAsStringSync(
    _emitBytes(
      'transparentPng',
      transparentPng,
      'RGBA PNG: opaque-red left half, transparent-black right half. The '
          'transparent half must survive image-stamp embedding as an /SMask '
          'instead of painting black.',
    ),
  );
  exports.add("export 'f_transparent_png.dart';");

  for (final spec in catalog) {
    final sw = Stopwatch()..start();
    final bytes = await spec.build(photoPng);
    final file = 'f_${spec.name}.dart';
    File('$_generatedDir/$file').writeAsStringSync(_emit(spec, bytes));
    exports.add("export '$file';");
    stdout.writeln(
      'fixtures: ${spec.name} — ${bytes.length} bytes in ${sw.elapsedMilliseconds}ms',
    );
  }

  File('$_generatedDir/fixtures.dart').writeAsStringSync('''
// GENERATED by tool/generate_fixtures.dart — do not edit.
// One import gives every generated fixture + its declared truths.

${exports.join('\n')}
''');
  // Canonicalize: emitted spacing must survive `dart format` untouched,
  // or every regeneration re-dirties the tree under the format gate.
  final fmt = Process.runSync(Platform.resolvedExecutable, [
    'format',
    _generatedDir,
  ]);
  if (fmt.exitCode != 0) {
    stderr.write(fmt.stderr);
    exitCode = fmt.exitCode;
    return;
  }

  stampFile.writeAsStringSync(stamp);
  stdout.writeln('fixtures: generated ${catalog.length} fixtures');
}

String _stampInputs() {
  final bytes = <int>[];
  for (final path in _inputs) {
    bytes.addAll(File(path).readAsBytesSync());
  }
  return sha256.convert(bytes).toString();
}

/// Emit raw bytes as a base64 Dart constant named [ident]. [doc] is the
/// `///` doc body for the constant (default describes the photo raster).
String _emitBytes(
  String ident,
  List<int> bytes, [
  String doc =
      'Photo-like 128x128 PNG (seeded noise) — JPEG-q50 beats its Flate\n'
      '/// stream, so optimizeImages finds work. Decoded once at first use.',
]) {
  final b64 = base64Encode(bytes);
  final chunks = <String>[
    for (var i = 0; i < b64.length; i += 76)
      "    '${b64.substring(i, (i + 76).clamp(0, b64.length))}'",
  ];
  return '''
// GENERATED by tool/generate_fixtures.dart — do not edit.
// Regenerate: make fixtures

import 'dart:convert';
import 'dart:typed_data';

/// $doc
final Uint8List $ident = base64Decode(_b64);

const _b64 =
${chunks.join('\n')};
''';
}

String _emit(FixtureSpec spec, List<int> bytes) {
  final ident = _camel(spec.name);
  final b64 = base64Encode(bytes);
  final chunks = <String>[
    for (var i = 0; i < b64.length; i += 76)
      "    '${b64.substring(i, (i + 76).clamp(0, b64.length))}'",
  ];
  final why = _wrapComment(spec.why);
  return '''
// GENERATED by tool/generate_fixtures.dart — do not edit.
// Regenerate: make fixtures
//
$why

import 'dart:convert';
import 'dart:typed_data';

/// dart-pdf-produced fixture bytes (decoded once at first use).
final Uint8List f$ident = base64Decode(_b64);

/// Declared ground truth — tests assert against THIS, never against
/// re-derived engine output.
const f${ident}Truth = (
${spec.truths.entries.map((e) => '  ${e.key}: ${_literal(e.value)},').join('\n')}
);

const _b64 =
${chunks.join('\n')};
''';
}

/// Word-wrap [text] into `// `-prefixed lines of at most 70 columns.
String _wrapComment(String text) {
  final lines = <String>[];
  var line = StringBuffer();
  for (final word in text.split(RegExp(r'\s+'))) {
    if (line.isNotEmpty && line.length + 1 + word.length > 67) {
      lines.add('// $line');
      line = StringBuffer();
    }
    if (line.isNotEmpty) line.write(' ');
    line.write(word);
  }
  if (line.isNotEmpty) lines.add('// $line');
  return lines.join('\n');
}

String _camel(String snake) =>
    snake.split('_').map((w) => w[0].toUpperCase() + w.substring(1)).join();

String _literal(Object v) => switch (v) {
  final String s => "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'",
  final List<Object> l => '[${l.map(_literal).join(', ')}]',
  _ => '$v', // int, double, bool
};

// ═══════════════════════════════════════════════════════════════════
// Photo-like PNG — the one raster fixture, built deterministically.
// ═══════════════════════════════════════════════════════════════════

/// Build the 128x128 photo-like PNG. Deterministic for a given [seed].
Uint8List buildPhotoPng({int seed = 42, int size = 128}) {
  // Raw image data: one filter byte (0 = none) per scanline, then RGB
  // triples. Gradient base + seeded noise defeats Flate, feeds JPEG.
  var state = seed & 0xffffffff;
  int next() {
    // Numerical Recipes LCG — small, deterministic, good enough for noise.
    state = (state * 1664525 + 1013904223) & 0xffffffff;
    return state >>> 16;
  }

  final raw = BytesBuilder(copy: false);
  for (var y = 0; y < size; y++) {
    raw.addByte(0); // filter: none
    for (var x = 0; x < size; x++) {
      final gradient = (x + y) * 255 ~/ (2 * size);
      int channel() => (gradient + (next() & 0x7f) - 64).clamp(0, 255);
      raw
        ..addByte(channel())
        ..addByte(channel())
        ..addByte(channel());
    }
  }

  final idat = ZLibCodec().encode(raw.takeBytes());
  return _assemblePng(size, size, Uint8List.fromList(idat));
}

/// Build a [size]×[size] RGBA (colour type 6) PNG: opaque red on the
/// left half, fully transparent black on the right half. The transparent
/// half must survive image-stamp embedding as an /SMask, not paint black.
Uint8List buildTransparentPng({int size = 32}) {
  // Raw image data: one filter byte (0 = none) per scanline, then RGBA
  // quads. Left half opaque red, right half transparent black.
  final raw = BytesBuilder(copy: false);
  final half = size ~/ 2;
  for (var y = 0; y < size; y++) {
    raw.addByte(0); // filter: none
    for (var x = 0; x < size; x++) {
      if (x < half) {
        raw
          ..addByte(255) // R
          ..addByte(0) // G
          ..addByte(0) // B
          ..addByte(255); // A — opaque
      } else {
        raw
          ..addByte(0) // R
          ..addByte(0) // G
          ..addByte(0) // B
          ..addByte(0); // A — transparent
      }
    }
  }

  final idat = ZLibCodec().encode(raw.takeBytes());
  return _assemblePng(size, size, Uint8List.fromList(idat), colorType: 6);
}

/// Wrap IDAT bytes in the PNG container: signature, IHDR, IDAT, IEND.
/// [colorType] is the PNG colour type byte: 2 = truecolour RGB (default),
/// 6 = truecolour with alpha (RGBA).
Uint8List _assemblePng(
  int width,
  int height,
  Uint8List idat, {
  int colorType = 2,
}) {
  final out = BytesBuilder(copy: false);
  out.add(const [137, 80, 78, 71, 13, 10, 26, 10]); // PNG signature

  final ihdr = BytesBuilder(copy: false)
    ..add(_u32(width))
    ..add(_u32(height))
    ..addByte(8) // bit depth
    ..addByte(colorType) // colour type: 2 = RGB, 6 = RGBA
    ..addByte(0) // compression
    ..addByte(0) // filter
    ..addByte(0); // interlace
  _chunk(out, 'IHDR', ihdr.takeBytes());
  _chunk(out, 'IDAT', idat);
  _chunk(out, 'IEND', Uint8List(0));
  return out.takeBytes();
}

void _chunk(BytesBuilder out, String type, Uint8List data) {
  final typeBytes = ascii.encode(type);
  out.add(_u32(data.length));
  out.add(typeBytes);
  out.add(data);
  final crcInput = BytesBuilder(copy: false)
    ..add(typeBytes)
    ..add(data);
  out.add(_u32(_crc32(crcInput.takeBytes())));
}

Uint8List _u32(int v) => Uint8List(4)..buffer.asByteData().setUint32(0, v);

int _crc32(Uint8List bytes) {
  var crc = 0xffffffff;
  for (final b in bytes) {
    crc ^= b;
    for (var i = 0; i < 8; i++) {
      crc = (crc & 1) != 0 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1;
    }
  }
  return crc ^ 0xffffffff;
}
