#!/bin/bash
# Stamp all release artifacts for a given tag. Single source of truth.
#
# Usage:
#   ./tool/stamp_release.sh v1.0.0-dev.0
#
# What it does (in order):
#   1. Stamps version into pubspec.yaml
#   2. Stamps version into lib/src/version.dart
#   3. For prereleases: copies CHANGELOG.pre.md → CHANGELOG.md
#   4. Appends commit list to CHANGELOG.md
#   5. Generates asset hashes from GitHub Release API (requires gh + GH_TOKEN)
#
# Requires: gh CLI authenticated (GH_TOKEN env var or gh auth login)
# Run from package root.

set -euo pipefail

if [ -z "${1:-}" ]; then
  echo "Usage: $0 <tag>"
  echo "Example: $0 v1.0.0-dev.0"
  exit 1
fi

TAG="$1"
VERSION="${TAG#v}"
REPO="${GITHUB_REPOSITORY:-whuppi/pdf_manipulator}"

echo "=== Stamping $TAG (version: $VERSION) ==="

# ── 1. pubspec.yaml ─────────────────────────────────────────────────

sed -i.bak "s/^version: .*/version: $VERSION/" pubspec.yaml && rm -f pubspec.yaml.bak
echo "  pubspec.yaml → $VERSION"

# ── 2. version.dart ─────────────────────────────────────────────────

sed -i.bak "s/const packageVersion = '[^']*'/const packageVersion = '$VERSION'/" lib/src/version.dart && rm -f lib/src/version.dart.bak
echo "  version.dart → $VERSION"

# ── 3. Changelog (prerelease swap) ──────────────────────────────────

if [[ "$VERSION" == *-* ]]; then
  cp CHANGELOG.pre.md CHANGELOG.md
  echo "  CHANGELOG.md ← CHANGELOG.pre.md (prerelease)"
fi

# ── 4. Append commit list ───────────────────────────────────────────

PREV_TAG=$(git tag --sort=-v:refname | grep '^v' | grep -v "^${TAG}$" | head -1 || true)
if [ -n "$PREV_TAG" ]; then
  COMMITS=$(git log "$PREV_TAG".."$TAG" --oneline --no-decorate 2>/dev/null || true)
else
  COMMITS=$(git log "$TAG" --oneline --no-decorate 2>/dev/null || true)
fi

if [ -n "$COMMITS" ]; then
  COUNT=$(echo "$COMMITS" | grep -c . || true)
  COMMIT_LIST=$(echo "$COMMITS" | sed 's/^/- /')
  printf '\n<details><summary>Commits since %s (%s)</summary>\n\n%s\n\n</details>\n' \
    "${PREV_TAG:-initial}" "$COUNT" "$COMMIT_LIST" >> CHANGELOG.md
  echo "  CHANGELOG.md += $COUNT commits"
else
  echo "  CHANGELOG.md (no commits to append)"
fi

# ── 5. Asset hashes from GitHub API ─────────────────────────────────

HASH_FILE="lib/src/hook/asset_hashes.dart"

if ! command -v gh &>/dev/null; then
  echo "  ⚠ gh CLI not found — skipping asset hashes"
elif ! gh api "repos/$REPO/releases/tags/$TAG" --silent 2>/dev/null; then
  echo "  ⚠ No GitHub Release for $TAG — skipping asset hashes"
else
  ASSETS=$(gh api "repos/$REPO/releases/tags/$TAG" \
    --jq '.assets[] | select(.digest != null and (.name | startswith("wasm-") | not) and (.name | startswith("Source") | not)) | "\(.name)\t\(.digest)"')

  if [ -z "$ASSETS" ]; then
    echo "  ⚠ No assets with digests — skipping asset hashes"
  else
    {
      echo "// Hashes of pre-built native binaries downloaded by the build hook."
      echo "// Generated by tool/stamp_release.sh from GitHub Release API digests."
      echo "//"
      echo "// The build hook verifies downloaded files against these hashes."
      echo "// Hash mismatch → re-download. Correct → use cached. Missing → download."
      echo ""
      echo "const Map<String, String> assetHashesSha256 = {"
      echo "$ASSETS" | sort | while IFS=$'\t' read -r name digest; do
        hash="${digest#sha256:}"
        echo "  '$name': '$hash',"
        echo "  $name ... ${hash:0:12}..." >&2
      done
      echo "};"
    } > "$HASH_FILE"
    HASH_COUNT=$(echo "$ASSETS" | grep -c . || true)
    echo "  $HASH_FILE → $HASH_COUNT hashes"
  fi
fi

echo ""
echo "=== Done. Ready for: dart pub publish --force ==="
