// Generates hook/asset_hashes.dart from GitHub Release binaries.
//
// Run after CI uploads release binaries:
//   dart run tool/write_asset_hashes.dart v1.0.0
//
// Downloads each binary, computes SHA256, writes the hashes file.

import 'dart:io';
import 'package:crypto/crypto.dart';

const _releaseRepo = 'https://github.com/whuppi/pdf_manipulator/releases/download';
const _outFile = 'hook/asset_hashes.dart';

const _platforms = [
  ('macos-arm64', 'libpdf_oxide.dylib'),
  ('macos-x64', 'libpdf_oxide.dylib'),
  ('ios-arm64', 'libpdf_oxide.a'),
  ('ios-sim-arm64', 'libpdf_oxide.a'),
  ('ios-sim-x64', 'libpdf_oxide.a'),
  ('android-arm64', 'libpdf_oxide.so'),
  ('android-arm', 'libpdf_oxide.so'),
  ('android-x64', 'libpdf_oxide.so'),
  ('android-x86', 'libpdf_oxide.so'),
  ('linux-x64', 'libpdf_oxide.so'),
  ('linux-arm64', 'libpdf_oxide.so'),
  ('windows-x64', 'pdf_oxide.dll'),
  ('windows-arm64', 'pdf_oxide.dll'),
];

void main(List<String> args) async {
  if (args.isEmpty) {
    stderr.writeln('Usage: dart run tool/write_asset_hashes.dart <tag>');
    stderr.writeln('Example: dart run tool/write_asset_hashes.dart v1.0.0');
    exit(1);
  }
  final tag = args[0];

  final hashes = <String, String>{};

  for (final (platform, libName) in _platforms) {
    final assetKey = '$platform-$libName';
    final url = '$_releaseRepo/$tag/$assetKey';
    stdout.write('  $assetKey ... ');

    try {
      final bytes = await _download(url);
      final hash = sha256.convert(bytes).toString();
      hashes[assetKey] = hash;
      print('${hash.substring(0, 12)}... (${(bytes.length / 1024 / 1024).toStringAsFixed(1)} MB)');
    } catch (e) {
      print('SKIP ($e)');
    }
  }

  final buf = StringBuffer();
  buf.writeln('// Hashes of pre-built native binaries downloaded by the build hook.');
  buf.writeln('// Generated by tool/write_asset_hashes.dart after a release build.');
  buf.writeln('//');
  buf.writeln('// The build hook verifies downloaded files against these hashes.');
  buf.writeln('// Hash mismatch → re-download. Correct → use cached. Missing → download.');
  buf.writeln();
  buf.writeln('const Map<String, String> assetHashesSha256 = {');
  for (final entry in hashes.entries) {
    buf.writeln("  '${entry.key}': '${entry.value}',");
  }
  buf.writeln('};');

  File(_outFile).writeAsStringSync(buf.toString());
  print('\nWrote ${hashes.length} hashes to $_outFile');
}

Future<List<int>> _download(String url) async {
  final client = HttpClient();
  try {
    var uri = Uri.parse(url);
    HttpClientResponse response;
    var redirects = 0;
    do {
      final req = await client.getUrl(uri);
      req.followRedirects = false;
      response = await req.close();
      if (response.isRedirect && response.headers.value('location') != null) {
        await response.drain<void>();
        uri = Uri.parse(response.headers.value('location')!);
        redirects++;
      } else {
        break;
      }
    } while (redirects < 5);

    if (response.statusCode != 200) {
      await response.drain<void>();
      throw StateError('HTTP ${response.statusCode}');
    }

    final chunks = <List<int>>[];
    await for (final chunk in response) {
      chunks.add(chunk);
    }
    return chunks.expand((c) => c).toList();
  } finally {
    client.close();
  }
}
