// Generates hook/asset_hashes.dart from GitHub Release asset digests.
//
// Run after CI uploads release binaries:
//   dart run tool/write_asset_hashes.dart v1.0.0
//
// Uses the GitHub API to read SHA256 digests — zero binary downloads.

import 'dart:convert';
import 'dart:io';

const _repo = 'whuppi/pdf_manipulator';
const _outFile = 'hook/asset_hashes.dart';

void main(List<String> args) async {
  if (args.isEmpty) {
    stderr.writeln('Usage: dart run tool/write_asset_hashes.dart <tag>');
    stderr.writeln('Example: dart run tool/write_asset_hashes.dart v1.0.0');
    exit(1);
  }
  final tag = args[0];

  final result = await Process.run('gh', [
    'api', 'repos/$_repo/releases/tags/$tag',
    '--jq', '.assets[] | {name: .name, digest: .digest}',
  ]);

  if (result.exitCode != 0) {
    stderr.writeln('Failed to query release $tag: ${result.stderr}');
    exit(1);
  }

  final hashes = <String, String>{};
  for (final line in (result.stdout as String).trim().split('\n')) {
    if (line.isEmpty) continue;
    final asset = jsonDecode(line) as Map<String, dynamic>;
    final name = asset['name'] as String;
    final digest = asset['digest'] as String?;

    if (name.startsWith('Source') || name.startsWith('wasm-')) continue;
    if (digest == null || !digest.startsWith('sha256:')) {
      print('  $name ... SKIP (no digest)');
      continue;
    }

    final hash = digest.substring('sha256:'.length);
    hashes[name] = hash;
    print('  $name ... ${hash.substring(0, 12)}...');
  }

  final buf = StringBuffer();
  buf.writeln('// Hashes of pre-built native binaries downloaded by the build hook.');
  buf.writeln('// Generated by tool/write_asset_hashes.dart from GitHub Release API digests.');
  buf.writeln('//');
  buf.writeln('// The build hook verifies downloaded files against these hashes.');
  buf.writeln('// Hash mismatch → re-download. Correct → use cached. Missing → download.');
  buf.writeln();
  buf.writeln('const Map<String, String> assetHashesSha256 = {');
  for (final entry in hashes.entries.toList()..sort((a, b) => a.key.compareTo(b.key))) {
    buf.writeln("  '${entry.key}': '${entry.value}',");
  }
  buf.writeln('};');

  File(_outFile).writeAsStringSync(buf.toString());
  print('\nWrote ${hashes.length} hashes to $_outFile');
}
