name: Package Test (Web)
description: Build WASM + run package tests on all 3 web modes via Makefile

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-web-testing
    - name: "Pub get"
      shell: bash
      run: fvm dart pub get --no-example
    - name: "Web JSPI"
      shell: bash
      run: make test-ops-jspi
    - name: "Web Atomics"
      shell: bash
      run: make test-ops-atomics
    - name: "Web OPFS"
      shell: bash
      run: make test-ops-opfs
